package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # MIT

java_library(
    name = "nopb-worker",
    srcs = [
        "Hub.java",
        "WorkRequest.java",
        "WorkResponse.java",
    ],
)
