local_repository(
    name = "main",
    path = "..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_fuzzing",
    sha256 = "5e51c8b51b01a124ce967cbf64aa18ee40488feb42bfa91911b2fa7c48c417c1",
    strip_prefix = "rules_fuzzing-2548aeae56e911b09b2ea879b94f30ae3a01dc50",
    urls = ["https://github.com/bazelbuild/rules_fuzzing/archive/2548aeae56e911b09b2ea879b94f30ae3a01dc50.zip"],
)

load("@rules_fuzzing//fuzzing:repositories.bzl", "rules_fuzzing_dependencies")

rules_fuzzing_dependencies(jazzer = True)

load("@rules_fuzzing//fuzzing:init.bzl", "rules_fuzzing_init")

rules_fuzzing_init()

load("@jazzer//:repositories.bzl", "jazzer_dependencies")

jazzer_dependencies()

load("@jazzer//:init.bzl", "jazzer_init")

jazzer_init()
