name: Fuzz
on: [push]
jobs:

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bazelbuild/setup-bazelisk@v1

      - name: Install deps
        run: sudo apt-get install clang libunwind-dev libblocksruntime-dev

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/fuzz
          bazel build --config=jazzer //:ReaderFuzzer_run

      # TODO(eustas): download corpus

      - name: Fuzz
        run: |
          mkdir -p ${RUNNER_TEMP}/fuzzing-corpus
          cd ${GITHUB_WORKSPACE}/fuzz
          bazel run --config=jazzer //:ReaderFuzzer_run -- \
            --timeout_secs=3600 \
            --fuzzing_output_root=${RUNNER_TEMP}/new-corpus \
            --corpus_dir=${RUNNER_TEMP}/fuzzing-corpus

      - uses: actions/upload-artifact@v2
        with:
          name: corpus
          path: ${{ runner.temp }}/new-corpus/corpus
          if-no-files-found: error
