name: Fuzz
on: [push]
jobs:

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bazelbuild/setup-bazelisk@v1

      - name: Cache corpus
        id: cache-corpus
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/fuzzing-corpus
          key: corpus

      - name: Install deps
        run: sudo apt-get install clang libunwind-dev libblocksruntime-dev

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/fuzz
          bazel build --config=jazzer //:ReaderFuzzer_run

      - name: Fuzz
        run: |
          cd ${GITHUB_WORKSPACE}/fuzz
          mkdir -p ${RUNNER_TEMP}/fuzzing-corpus
          bazel run --config=jazzer //:ReaderFuzzer_run -- \
            --timeout_secs=300 \
            --fuzzing_output_root=${RUNNER_TEMP}/new-corpus \
            --corpus_dir=${RUNNER_TEMP}/fuzzing-corpus
          cp ${RUNNER_TEMP}/new-corpus/* ${RUNNER_TEMP}/fuzzing-corpus/
