name: Fuzz
on: [push]
jobs:

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bazelbuild/setup-bazelisk@v1

      - name: Install deps
        run: sudo apt-get install clang libunwind-dev libblocksruntime-dev

      - name: Build & Fuzz
        run: |
          cd fuzz
          bazel run --config=jazzer //:ReaderFuzzer_run
