name: Fuzz
on: [push]
jobs:

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bazelbuild/setup-bazelisk@v1

      - name: Install deps
        run: sudo apt-get install clang libunwind-dev libblocksruntime-dev

      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/fuzz
          bazel build --config=jazzer //:ReaderFuzzer_run

      - name: Fuzz
        run: |
          cd ${GITHUB_WORKSPACE}/fuzz
          bazel run --config=jazzer //:ReaderFuzzer_run
